JovemProgramadorMvc2/Models/AlunoModel.cs
namespace JovemProgramadorMvc2.Models
{
    public class AlunoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public int Idade { get; set; }
        public string Contato { get; set; }
        public string Cep { get; set; }
        public string Operacao { get; set; }
    }
}

JovemProgramadorMvc2/Models/EnderecoModel.cs
namespace JovemProgramadorMvc2.Models
{
    public class EnderecoModel
    {
        public int Id { get; set; }
        public int IdAluno { get; set; }
        public string logradouro { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string localidade { get; set; }
        public string uf { get; set; }
        public string ddd { get; set; }

        public EnderecoModel()
        {

        }
    }
}

JovemProgramadorMvc2/Models/ErrorViewModel.cs
using System;

namespace JovemProgramadorMvc2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JovemProgramadorMvc2/Models/ProfessorModel.cs
namespace JovemProgramadorMvc2.Models
{
    public class ProfessorModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Idade { get; set; }
        public string Contato { get; set; }
        public string Cep { get; set; }
    }
}

JovemProgramadorMvc2/Controllers/AlunoController.cs
using JovemProgramadorMvc2.Models;
using JovemProgramadorMVC2.Data.Repositorio.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace JovemProgramadorMvc2.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IAlunoRepositorio _alunorepositorio;

        public AlunoController(IConfiguration configuration, IAlunoRepositorio alunoRepositorio)
        {
            _configuration = configuration;
            _alunorepositorio = alunoRepositorio;
        }
        public IActionResult Index(AlunoModel filtroAluno)
        {
            List<AlunoModel> aluno = new();
            if (filtroAluno.Idade >0)
            {
                aluno = _alunorepositorio.FiltroIdade(filtroAluno.Idade, filtroAluno.Operacao);
            }
            if (filtroAluno.Nome != null)
            {
                aluno = _alunorepositorio.FiltroNome(filtroAluno.Nome);
            }
            if (filtroAluno.Contato != null)
            {
                aluno = _alunorepositorio.FiltroContato(filtroAluno.Contato);
            }

            if(filtroAluno.Id == 0)
            {
                aluno = _alunorepositorio.BuscarAlunos();
            }
            return View(aluno);
        }

        public IActionResult Adicionar()
        {
            return View();
        }
        
        public IActionResult Salvo()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            var aluno = _alunorepositorio.BuscarId(id);
            return View("Editar", aluno);
        }

        public IActionResult Atualizar(AlunoModel aluno)
        {
            var retorno = _alunorepositorio.Atualizar(aluno);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Endereco(AlunoModel aluno)
        {
            var retorno = _alunorepositorio.BuscarId(aluno.Id);
            aluno = retorno;
            EnderecoModel enderecoModel = new();

            try
            {
                var cep = aluno.Cep.Replace("-", "");

                using var client = new HttpClient();
                var result = await client.GetAsync(_configuration.GetSection("ApiCep")["BaseUrl"] + cep + "/json");

                if (result.IsSuccessStatusCode)
                {
                    enderecoModel = JsonSerializer.Deserialize<EnderecoModel>(
                        await result.Content.ReadAsStringAsync(), new JsonSerializerOptions() { });

                    if (enderecoModel.complemento == "")
                    {
                        enderecoModel.complemento = "nenhum";
                    }

                    if (enderecoModel.logradouro == "")
                    {
                        enderecoModel.logradouro = "nenhum";
                    }
                }
                else
                {
                    ViewData["mensagem"] = "Erro na busca do endereço!";
                    return View("Index");
                }

            }
            catch (Exception e)
            {
                ViewData["Mensagem"] = "Erro na requisição!";
                return View("Index");
            }


            return View("Endereco", enderecoModel);
        }

        [HttpPost]
        public IActionResult Inserir(AlunoModel aluno)
        {
            var retorno = _alunorepositorio.Inserir(aluno);
            if (retorno != null)
            {
                TempData["Mensagem2"] = "Dados gravados com sucesso!";
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult BuscarAlunos(AlunoModel aluno)
        {
            _alunorepositorio.BuscarAlunos();
            return RedirectToAction("Index");
        }

        public IActionResult Excluir(int id)
        {
            var retorno = _alunorepositorio.Excluir(id);
            if (retorno == true)
            {
                TempData["Mensagem3"] = "Aluno excluído com sucesso!";
            }
            else
            {
                TempData["Mensagem3"] = "Aluno não foi excluído!";
            }

            return RedirectToAction("Index");
        }
    }


}

JovemProgramadorMvc2/Controllers/ConhecimentosController.cs
using Microsoft.AspNetCore.Mvc;

namespace JovemProgramadorMvc2.Controllers
{
    public class ConhecimentosController : Controller
    {
        public ConhecimentosController()
        {

        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

JovemProgramadorMvc2/Controllers/HomeController.cs
using JovemProgramadorMvc2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace JovemProgramadorMvc2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JovemProgramadorMvc2/Controllers/InformacoesController.cs
using Microsoft.AspNetCore.Mvc;

namespace JovemProgramadorMvc2.Controllers
{
    public class InformacoesController : Controller
    {
        public InformacoesController()
        {

        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

JovemProgramadorMvc2/Controllers/ProfessoresController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using JovemProgramadorMvc2.Models;
using Microsoft.Extensions.Configuration;
using System;
using System.Net.Http;
using System.Text.Json;

namespace JovemProgramadorMvc2.Controllers
{
    public class ProfessoresController : Controller
    {

        private readonly IConfiguration _configuration;
        public ProfessoresController()
        {

        }


        public IActionResult Index()
        {
            return View();
        }

    }
}

JovemProgramadorMvc2/Views/Aluno/Adicionar.cshtml
@model AlunoModel

<form asp-controller="Aluno" asp-action="Inserir" method="post">
    <div class="text-left"></div>

    <div>

        <h1>
            Cadastrar Novo Aluno

            <script>
                function showAlert()
                {
                     window.alert("Aluno salvo com sucesso!!!");
                }
             </script>
        </h1>
    </div>

    <label for="inputtext" class="form-label">Nome</label>
    <input type="text" asp-for="Nome" class="col-4 form-control">

    <label for="inputtext" class="form-label">Idade</label>
    <input type="text" asp-for="Idade" class="col-2 form-control" placeholder="18">

    <label for="inputtext" class="form-label">Contato</label>
    <input type="text" asp-for="Contato" class="col-2 form-control" placeholder="(99) 9 9999-9999">

    <label for="inputtext" class="form-label">Email</label>
    <input type="text" asp-for="Email" class="col-3 form-control" placeholder="email@exemplo.com">

    <label for="inputtext" class="form-label">Cep</label>
    <input type="text" asp-for="Cep" class="col-2 form-control" placeholder="88000-000">

    <div class="text-center">
        <button class="btn btn-dark" onclick="showAlert()" role="button" type="submit">Salvar</button>


        <a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Index">Voltar</a>

    </div>
</form>

JovemProgramadorMvc2/Views/Aluno/Editar.cshtml
@model AlunoModel

<form asp-controller="Aluno" asp-action="Atualizar" method="post">
    <input type="hidden" asp-for="Id"/>

    
    <div class="text-left"></div>
    
    <div>

        <h1>
            Cadastrar Novo Aluno

            <script>
                function showAlert()
                {
                     window.alert("Aluno editado com sucesso!!!");
                }
             </script>
        </h1>
    </div>

    <label for="inputtext" class="form-label">Nome</label>
    <input type="text" asp-for="Nome" class="col-4 form-control">

    <label for="inputtext" class="form-label">Idade</label>
    <input type="text" asp-for="Idade" class="col-2 form-control" placeholder="18">

    <label for="inputtext" class="form-label">Contato</label>
    <input type="text" asp-for="Contato" class="col-2 form-control" placeholder="(99) 9 9999-9999">

    <label for="inputtext" class="form-label">Email</label>
    <input type="text" asp-for="Email" class="col-3 form-control" placeholder="email@exemplo.com">

    <label for="inputtext" class="form-label">Cep</label>
    <input type="text" asp-for="Cep" class="col-2 form-control" placeholder="88000-000">

    <div class="text-center">
        <button class="btn btn-dark" onclick="showAlert()" role="button" type="submit">Salvar</button>


        <a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Index">Voltar</a>

    </div>
</form>

JovemProgramadorMvc2/Views/Aluno/Endereco.cshtml
@model EnderecoModel



<div class="text-left">

    <div>

        <h1>Endereço</h1>
    </div>

    <label for="inputtext" class="form-label">Logradouro</label>
    <input type="text" class="col-4 form-control" asp-for="logradouro">

    <label for="inputtext" class="form-label">Complemento</label>
    <input type="text" class="col-4 form-control" asp-for="complemento">

    <label for="inputtext" class="form-label">Bairro</label>
    <input type="text" class="col-2 form-control" asp-for="bairro">

    <label for="inputtext" class="form-label">Localidade</label>
    <input type="text" class="col-2 form-control" asp-for="localidade">

    <label for="inputtext" class="form-label">UF</label>
    <input type="text" class="col-2 form-control" asp-for="uf">

    <label for="inputtext" class="form-label">DDD</label>
    <input type="text" class="col-1 form-control" asp-for="ddd">

    <div class="text-center">

        <a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Index">Voltar</a>
    </div>

JovemProgramadorMvc2/Views/Aluno/Filtros.cshtml
@model AlunoModel

<form asp-controller="Aluno" asp-action="Index" method="post" class="mb-3">
    <div class="mb-3">
        <label for="name" class="form-label">Idade</label>
        <div class="d-flex">
            <input type="text" asp-for="Idade" class="form-control col-md-1 mr-3" required>
            <select class="form-select" asp-for="Operacao">
                <option selected>Selecione uma opção</option>
                <option value="=">Idade Igual</option>
                <option value=">">Idade Maior</option>
                <option value="<">Idade Menor</option>
            </select>
        </div>

    </div>
    <div class="text-left">
        <button type="submit" class="btn btn-primary col-1"> Buscar</button>
    </div>

</form>

<form asp-controller="Aluno" asp-action="Index" method="post" class="mb-3">
    <div class="mb-3">
        <label for="name" class="form-label">Nome</label>
        <div class="d-flex">
            <input type="text" asp-for="Nome" class="form-control col-md-1 mr-3" required>
        </div>

    </div>
    <div class="text-left">
        <button type="submit" class="btn btn-primary col-1"> Buscar</button>
    </div>

</form>

<form asp-controller="Aluno" asp-action="Index" method="post">
    <div class="mb-3">
        <label for="name" class="form-label">Contato</label>
        <div class="d-flex">
            <input type="text" asp-for="Contato" class="form-control col-md-1 mr-3" required>
        </div>

    </div>
    <div class="text-left">
        <button type="submit" class="btn btn-primary col-1"> Buscar</button>
    </div>

</form>

    
<div class="text-center">
    <a class="btn btn-primary col-1" role="button" asp-controller="Aluno" asp-action="Index">Voltar</a>
</div>

JovemProgramadorMvc2/Views/Aluno/Index.cshtml
@model List<AlunoModel>

@if (ViewData["mensagem"] != null)
{
    <div class="alert-danger">
        @ViewData["mensagem"]
    </div>
}
<div class="text-left">


    <div>

        <h1>Dados dos Alunos</h1>
    </div>

    <div>


        <script>
            function showAlert()
            {
                 window.alert("Aluno excluído com sucesso!!!");
            }
        </script>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Idade</th>
                <th scope="col">Contato</th>
                <th scope="col">Cep</th>
            </tr>
        </thead>


        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (AlunoModel aluno in Model)
                {
                    <tr>
                        <td> @aluno.Nome </td>
                        <td> @aluno.Email</td>
                        <td> @aluno.Idade</td>
                        <td> @aluno.Contato</td>
                        <td> @aluno.Cep </td>
                        <td><a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Endereco" asp-route-cep="@aluno.Id">Endereço</a></td>
                        <td><a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Editar" asp-route-id="@aluno.Id">Editar</a></td>
                        <td><a class="btn btn-danger" type="button" onclick="showAlert()" asp-controller="Aluno" asp-action="Excluir" asp-route-id="@aluno.Id">Excluir</a></td>

                    </tr>
                }
            }
        </tbody>

    </table>

    <div class="text-center">
        <a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Adicionar">Adicionar Novo Aluno</a>
        <a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Filtros">Filtros Aluno</a>
        <a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Index"> Voltar</a>
    </div>

</div>

JovemProgramadorMvc2/Views/Aluno/Salvo.cshtml
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
    </symbol>
</svg>
<div class="alert alert-success d-center align-items-center text-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill" /></svg>

    Aluno adicionado com sucesso!
</div>

<div class="text-center">
    <a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Index">Voltar</a>
</div>

JovemProgramadorMvc2/Views/Conhecimentos/Index.cshtml
<div class="text-left">

    <div>

        <h1>Conhecimentos Adquiridos</h1>
    </div>
    <div>
        <p>Aspnet MVC</p>
        <p>Mocagem de dados</p>
        <p>Conexão com banco SQL</p>
        <p>Chamada de api externa</p>
    </div>

JovemProgramadorMvc2/Views/Home/Index.cshtml
@{
    ViewData["Inicio"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4" >Bem Vindo</h1>
    <p>Sobre o curso:</p>
    <p>O PROGRAMA de capacitação tecnológica para formação de jovens denominado JOVEM PROGRAMADOR, 
        tem como missão a capacitação tecnológica para formação de jovens programadores para atuação principalmente 
        em empresas do Estado de Santa Catarina, independentemente do local onde estejam instaladas. </p>
        <div class="d-grid gap-2 d-md-block">
</div>
</div>

JovemProgramadorMvc2/Views/Informacoes/Index.cshtml
<head>Informações</head>
<body class="text-center">
    <h1>Informações</h1>
    <p>Data de inicio do Curso: 01/07/2021</p>
    <p>Data de termino: 01/07/2022</p>
    <p>Coordenador: Junior Cunha</p>
    <p>Senac-Brusque</p>
    <p>Rua Manoel Borges 186, Porto Grande, Araquari</p>
    <p>(48)98440-6456</p>


</body>

JovemProgramadorMvc2/Views/Professores/Index.cshtml
@model EnderecoModel
<div class="text-left">

    <div>

        <h1>Dados dos Professores</h1>
    </div>

    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Idade</th>
      <th scope="col">Contato</th>
      <th scope="col">Cep</th>
    </tr>
  </thead>


  <tbody>

    <tr>
      <th scope="row">1</th>
      <td>Katia Schmitt Pollheim</td>
      <td>katiaschimittp@gmail.com</td>
      <td>28</td>
      <td>47 991774897</td>
      <td></td>
      <td>83350-665</td>
      <td><a class="btn btn-dark" type="button" asp-controller="Aluno" asp-action="Endereco" asp-route-cep="88350-665">Endereço</a></td>
    </tr>  
    
  </tbody>
  
</table>

<div class="text-center">
    <button type="button" class="btn btn-dark">Adicionar Novo Professor</button>
</div>


</div>

JovemProgramadorMvc2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jovem Programador MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Jovem Programador MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Professores" asp-action="Index">Professores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Conhecimentos" asp-action="Index">Conhecimentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Informacoes" asp-action="Index">Informações</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - JovemProgramadorMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>